;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attributes.Combat.Poise",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.Armor",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.ArmorPenetration",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.CritChance",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.CritDamage",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.MagicDamage",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.MagicPenetration",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.MagicResistance",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.MaxMana",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.MaxPoise",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.MaxStamina",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.PhysicalDamage",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary.Tenacity",DevComment="")
+GameplayTagList=(Tag="Attributes.Vital.Health",DevComment="")
+GameplayTagList=(Tag="Attributes.Vital.Mana",DevComment="")
+GameplayTagList=(Tag="Attributes.Vital.Stamina",DevComment="")
+GameplayTagList=(Tag="Event.Montage.SpawnProjectile",DevComment="Enviado desde el AnimNotify cuando es momento de spawnear el proyectil")
+GameplayTagList=(Tag="Message.HealthCrystal",DevComment="")
+GameplayTagList=(Tag="Message.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Message.ManaCrystal",DevComment="")
+GameplayTagList=(Tag="Message.ManaPotion",DevComment="")

